### PR TITLE
wrong content in "/etc/envirnment" by installer

### PR DESCRIPTION
**Pull request by Vitamin-X**
the file /etc/envirnment is just a path, but it looks like that

PATH="/bin"

### CODE REVIEW

**Comment by muhdidhamm** [comment]
hey why you put this "\$PATH\"??

**Comment by muhdidhamm** [comment]
it works, please merge it.

**Comment by Vitamin-X** [comment]
still new to github... but setted it to "ready for review"

**Comment by Vitamin-X** [comment]
seems like nobody cares

**Comment by Eeems** [comment]
You might want to update the title to be more specific as to what this is doing. It's up to @ej52 to merge it though.

**Comment by Vitamin-X** [comment]
there are only 8 pull requests so i gues thats not the problem, the last update was also 9 months ago

**Comment by Eeems** [comment]
> there are only 8 pull requests so i gues thats not the problem

There are two open from you with the same title, it's very confusing.

> the last update was also 9 months ago

It looks like @ej52 hasn't done anything on github since that date either.

**Comment by Vitamin-X** [comment]
but does the name matter anyway? i mean they are 8 of them, i would atleast take a look :D

changed them anyway...

**Comment by ej52** [comment]
Not relevant anymore due to https://github.com/ej52/proxmox-scripts/pull/146

**Pull request closed without merging**
