### PR TITLE
add debian support

### PR DESCRIPTION
**Pull request by Tropaion**
added debian support, testet with debian 10 lxc, throws two warnings but works.

### CODE REVIEW

**Comment by Tropaion** [comment]
I'm currently not using debian 11 but will probably upgrade in the future and edit the install file.
Adding a version checking shouldn't be difficult, I will soon look into it.

**Comment by xiaocang** [comment]
Hi @Tropaion, now openresty has been packaged for debian 11

**Comment by SkateWarp** [comment]
Hello, I'm getting this error:
imagen

It's while updating an existing NPM container.

**Comment by Tropaion** [comment]
You can try the branch for debian I made, for me it works perfectly fine, I use the latest version of NPM
https://github.com/Tropaion/proxmox-scripts

**Comment by SkateWarp** [comment]
> You can try the branch for debian I made, for me it works perfectly fine, I use the latest version of NPM https://github.com/Tropaion/proxmox-scripts

Actually, I'm using your branch.

**Comment by Tropaion** [comment]
Then I don't know, I don't get any errors. Probably something wrong with your network interface (eth0).

**Comment by ej52** [comment]
@Tropaion Thanks for the PR, however I have decided to merge debian/ubuntu install scripts in one #62

**Pull request closed without merging**
